import Head from 'next/head';
import styles from "@/styles/Home.module.css";
import { useContext, useEffect, useState } from 'react';
import { IBlogPost } from "../../types/IBlogPost";
import { IShopItem } from "../../types/IShopItem";
import PartnerSection from '@/components/partners';
import { ShopContext } from '@/ShopContext';

export default function Home(setShoppingList) {
  const {items} = useContext(ShopContext);
  const [blogPosts, setBlogs] = useState<IBlogPost[]>([]);
  const [shopItems, setShowItems] = useState<IShopItem[]>([]);
  const [currentItemIndex, setCurrentItemIndex] = useState<number>(0);

  const fetchData = async (url: string, setter: React.Dispatch<React.SetStateAction<any[]>>) => {
    try {
      const response = await fetch(url);
      if (response.ok) {
        const data = await response.json();
        setter(data.data);
      } else {
        console.error('Failed to fetch data');
      }
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  useEffect(() => {
    fetchData('http://localhost:1337/api/shops?populate=image&filters[$and][0][showroom][$eq]=true', setShowItems);
  }, []);

  const handleItemClick = (index: number) => {
    setCurrentItemIndex(index);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-full'>
        {/* <PartnerSection/> */}
      </main>
    </>
  );
}
